server:
  port: 8002
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/see
    username: root
    password: lyt20040705
  mail: #邮箱smtp服务配置
    host: smtp.163.com #服务器邮箱地址
    username: tjsemae@163.com #账号
    password: PUyJk34YURb8jgmz #授权码
    protocol: smtp #一般无需修改
    default-encoding: utf-8
    port: 25
    from: tjsemae@163.com
  # redis配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    password: 123456
    database: 0
    # 连接超时时间
    timeout: 10s
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1m
        time-between-eviction-runs: 1000ms

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  thymeleaf:
    enabled: false
    check-template-location: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    template-resolver-order: 2

  mvc:
    servlet:
      load-on-startup: 1
    path match:
      matching-strategy: ant_path_matcher

# 设置控制台输出mybatis-plus相关日志
mybatis-plus:
  # 配置 XML 文件路径（支持通配符）
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

tencent:
  cloud:
    cos: #腾讯云cos服务配置
      region: ??
      secretId: ??
      secretKey: ??
      bucket: vse-back-end-bucket-??
      baseUrl: https://??


logging:
  level:
    com.baomidou.mybatisplus.core.MybatisPlusInterceptor: debug
    root: info
    com.your.package: debug
    com.baomidou.mybatisplus: debug

# SpringDoc配置
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    csrf:
      enabled: false
    try-it-out-enabled: true
    persist-authorization: true
  api-docs:
    enabled: true
  packages-to-scan: com.backend.vse.controller
  paths-to-match: /**
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  use-management-port: false
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  override-with-generic-response: false

jwt:
  dev-mode: true # true=开发模式直接放行，false=生产模式校验token
